# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux
  - osx

matrix:
  include:
  - r: devel
    env: _R_CHECK_SYSTEM_CLOCK_=false
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""), verbose = TRUE)'
      skip_cleanup: true
  - r: oldrel
  allow_failures:
  - r: devel
